version: '2.2'

services:
    mongodb:
        image: mongo:3.4
        expose:
            - 27017
        volumes:
            - ./mongodb-data:/data/db
        restart: unless-stopped

    db:
        image: db:1.0
        volumes:
            - ./dump.sql.gz:/docker-entrypoint-initdb.d/z2-dump.sql.gz
            - ./postgresql-data:/var/lib/postgresql
        environment:
            - "POSTGRES_PASSWORD=1111"
            - "POSTGRES_USER=sweb"
            - "POSTGRES_DB=swebcore"
        expose:
            - "5432"
        entrypoint:
            - /docker-entrypoint.sh
        command:
            - postgres
        restart: unless-stopped

    sweb:
        image: sweb:5.2.7
        volumes:
            - ./override.properties:/conf/override.properties #Inject the configurations
        links:
            - db
            - nlptool
        restart: unless-stopped
        ports:
            - "0.0.0.0:8081:8080"
        command: /bin/wait-for db:5432 -t 600 -- /usr/bin/java ${JAVAOPTS} -jar /sweb-webapi-runtime.jar

    kos:
        image: kos:1.0
        depends_on:
            - sweb
            - mongodb
        volumes:
            - './kos-apps:/kos/apps'
            - './config.js:/kos/kos-core/config.js'
            - './etype_lattice_cache.json:/kos/kos-core/etype_lattice.json'
        ports:
            - "5001:5000"
        expose:
            - "5001"
        restart: unless-stopped
        command: /bin/wait-for -t 60 mongodb:27017 -- /bin/wait-for -t 780 sweb:8080 -- /bin/sh -c "cd /kos/kos-core && node index.js"


    karmalinker:
        image: karmalinker:2.4-r1
        volumes:
            - './karma-pyAddons:/root/karma/python'
        environment:
            - SCROLL_SERVICE_URL=http://sweb:8080
            - KOS_SERVICE_URL=http://localhost:5001/
        restart: unless-stopped
        ports:
            - "7000:7000"

    converter:
        image: rdf2eml:1.0
        restart: unless-stopped
        ports:
            - "6000:6000"
        command:
            - "/bin/java"
            - "-jar"
            - "app.jar"
            - "--sweb.url=http://sweb:8080/"
            - "--server.port=6000"

    ihs:
        image: ihs:1.9
        environment:
            - APP_LANGUAGE=en
            - APP_PORT=4000
            - SWEB_HOST=sweb
            - SWEB_PORT=8080
            - KOS_HOST=kos
            - KOS_PORT=5000
            - KOS_AUTH_TOKEN=0397d5a90613feea401a3a298de551fb
            - CONVERTER_HOST=converter
            - CONVERTER_PORT=6000
        restart: unless-stopped
        ports:
            - "4000:4000"
        volumes:
            - './IHS-log:/util/logger/logs'
            - './IHS-resources:/resources'
            - './karma-pyAddons:/root/karma/python'
        command: npm run start-ihs

    nlptool:
        image: nlp:4.0.1
        expose:
            - 8000
